import { existsSync } from 'fs';
import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { systemPythonBin } from './python-bin';
import { runCommand } from './shell';

export const PR_COVERAGE_VENV = '.pr-coverage-venv';

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\"'\"'`)}'`;
}

export function venvDir(repoDir: string): string {
  return join(repoDir, PR_COVERAGE_VENV);
}

export function venvPython(repoDir: string): string {
  return join(venvDir(repoDir), 'bin', 'python');
}

export function venvActivateScript(repoDir: string): string {
  return join(venvDir(repoDir), 'bin', 'activate');
}

export function wrapWithVenvActivate(command: string, repoDir: string): string {
  const activate = venvActivateScript(repoDir);
  return `source ${shellQuote(activate)} && ${command}`;
}

export async function ensurePythonVenv(repoDir: string): Promise<void> {
  if (existsSync(venvPython(repoDir))) return;

  const result = await runCommand(
    `${systemPythonBin()} -m venv ${PR_COVERAGE_VENV}`,
    repoDir,
  );
  if (result.exitCode !== 0) {
    const output = `${result.stdout}\n${result.stderr}`.slice(-2000);
    throw new Error(
      `Failed to create Python virtualenv (exit ${result.exitCode}): ${output}`,
    );
  }
}

async function hasAsyncioPytestConfig(repoDir: string): Promise<boolean> {
  const pytestIni = join(repoDir, 'pytest.ini');
  if (existsSync(pytestIni)) {
    const content = await readFile(pytestIni, 'utf-8');
    if (/asyncio_mode\s*=/i.test(content)) return true;
  }

  const pyproject = join(repoDir, 'pyproject.toml');
  if (existsSync(pyproject)) {
    const content = await readFile(pyproject, 'utf-8');
    if (/asyncio_mode\s*=/i.test(content)) return true;
  }

  for (const path of [
    join(repoDir, 'conftest.py'),
    join(repoDir, 'tests', 'conftest.py'),
  ]) {
    if (!existsSync(path)) continue;
    const content = await readFile(path, 'utf-8');
    if (/pytest_asyncio|asyncio_mode/i.test(content)) return true;
  }

  return false;
}

/** Ensure pytest-asyncio works and local packages are importable. */
export async function ensurePythonTestConfig(repoDir: string): Promise<void> {
  if (!(await hasAsyncioPytestConfig(repoDir))) {
    const pytestIni = join(repoDir, 'pytest.ini');
    if (!existsSync(pytestIni)) {
      await writeFile(
        pytestIni,
        [
          '[pytest]',
          'asyncio_mode = auto',
          'pythonpath = .',
          '',
        ].join('\n'),
        'utf-8',
      );
    }
  }

  const testsDir = join(repoDir, 'tests');
  const conftestPath = existsSync(testsDir)
    ? join(testsDir, 'conftest.py')
    : join(repoDir, 'conftest.py');

  if (!existsSync(conftestPath)) {
    await writeFile(
      conftestPath,
      [
        '"""Generated by PR Coverage Assistant — enables async pytest."""',
        'import sys',
        'from pathlib import Path',
        '',
        '_root = Path(__file__).resolve().parent',
        'if _root.name == "tests":',
        '    _root = _root.parent',
        'if str(_root) not in sys.path:',
        '    sys.path.insert(0, str(_root))',
        '',
      ].join('\n'),
      'utf-8',
    );
  }
}
